import { test } from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import { createTestDb } from './test-db.ts';
import { handleImageUpload, type MediaLike } from '../../pages/api/admin/images/index.ts';
import type { D1Like, D1StatementLike } from './db.ts';

// ---------- media fake: in-memory R2 that records puts/deletes ----------

class FakeMedia implements MediaLike {
  objects = new Map<string, Uint8Array>();
  puts: string[] = [];
  deletes: string[] = [];

  async put(key: string, value: ArrayBuffer | Uint8Array) {
    this.puts.push(key);
    this.objects.set(key, value instanceof Uint8Array ? value : new Uint8Array(value));
  }
  async delete(key: string) {
    this.deletes.push(key);
    this.objects.delete(key);
  }
}

// ---------- real image fixtures generated by sharp ----------

async function fixture(mime: 'image/jpeg' | 'image/png' | 'image/webp'): Promise<ArrayBuffer> {
  const b = sharp({ create: { width: 120, height: 80, channels: 3, background: { r: 210, g: 120, b: 60 } } });
  const buf = await (mime === 'image/jpeg' ? b.jpeg() : mime === 'image/png' ? b.png() : b.webp()).toBuffer();
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
}

function formRequest(body: FormData): Request {
  return new Request('http://localhost/api/admin/images/', { method: 'POST', body });
}

const upload = (media: MediaLike, db: D1Like, body: FormData) =>
  handleImageUpload({ db, media, request: formRequest(body) });

const countImages = (db: D1Like) =>
  db.prepare('SELECT COUNT(*) AS n FROM images').first<{ n: number }>().then((r) => r?.n ?? 0);

function withFile(file: Blob, name = 'upload.bin'): FormData {
  const fd = new FormData();
  fd.append('file', file, name);
  return fd;
}

interface UploadBody {
  image: {
    id: string;
    r2Original: string;
    width: number;
    height: number;
    bytes: number;
    mime: string;
    duplicate?: boolean;
  };
}

const resImage = async (res: Response) => {
  const body = (await res.json()) as UploadBody;
  return body.image;
};

// ---------- valid uploads ----------

test('upload endpoint: JPEG -> 200, real dims, D1 row, R2 object', async () => {
  const db = createTestDb();
  const media = new FakeMedia();
  const res = await upload(media, db, withFile(new File([await fixture('image/jpeg')], 'photo.jpg', { type: 'image/jpeg' })));
  assert.equal(res.status, 200);
  const image = await resImage(res);
  assert.equal(image.width, 120);
  assert.equal(image.height, 80);
  assert.equal(image.mime, 'image/jpeg');
  assert.ok(image.bytes > 0);
  assert.match(image.id, /^[0-9a-f-]{36}$/i);

  const row = await db.prepare('SELECT * FROM images WHERE id = ?').bind(image.id).first();
  assert.ok(row);
  assert.equal((row as { width: number }).width, 120);
  assert.equal((row as { height: number }).height, 80);
  assert.ok(media.objects.has(image.r2Original), 'R2 object stored');
  assert.equal(media.deletes.length, 0);
});

test('upload endpoint: PNG -> 200, correct dims/mime', async () => {
  const db = createTestDb();
  const media = new FakeMedia();
  const res = await upload(media, db, withFile(new File([await fixture('image/png')], 'photo.png', { type: 'image/png' })));
  assert.equal(res.status, 200);
  const image = await resImage(res);
  assert.equal(image.width, 120);
  assert.equal(image.height, 80);
  assert.equal(image.mime, 'image/png');
  assert.ok(media.objects.has(image.r2Original));
});

test('upload endpoint: WebP -> 200, correct dims/mime', async () => {
  const db = createTestDb();
  const media = new FakeMedia();
  const res = await upload(media, db, withFile(new File([await fixture('image/webp')], 'photo.webp', { type: 'image/webp' })));
  assert.equal(res.status, 200);
  const image = await resImage(res);
  assert.equal(image.width, 120);
  assert.equal(image.height, 80);
  assert.equal(image.mime, 'image/webp');
  assert.ok(media.objects.has(image.r2Original));
});

test('upload endpoint: duplicate hash returns the existing id, no new R2 object', async () => {
  const db = createTestDb();
  const media = new FakeMedia();
  const img = await fixture('image/png');
  const first = await upload(media, db, withFile(new File([img], 'a.png', { type: 'image/png' })));
  assert.equal(first.status, 200);
  const firstImage = await resImage(first);

  const dup = await upload(media, db, withFile(new File([img], 'b.png', { type: 'image/png' })));
  assert.equal(dup.status, 200);
  const dupImage = await resImage(dup);
  assert.equal(dupImage.duplicate, true);
  assert.equal(dupImage.id, firstImage.id);
  assert.equal(media.puts.length, 1, 'no second R2 put for a duplicate');
  const { results } = await db.prepare('SELECT id FROM images WHERE sha256 = (SELECT sha256 FROM images WHERE id = ?)').bind(firstImage.id).all();
  assert.equal(results.length, 1);
});

// ---------- invalid uploads ----------

test('upload endpoint: text file renamed .png is rejected (422), no D1/R2 residue', async () => {
  const db = createTestDb();
  const media = new FakeMedia();
  const res = await upload(media, db, withFile(new File(['this is not an image at all, just plain text bytes'], 'fake.png', { type: 'image/png' })));
  assert.equal(res.status, 422);
  const body = (await res.json()) as { error: { code: string } };
  assert.equal(body.error.code, 'not_an_image');
  assert.equal((await countImages(db)), 0);
  assert.equal(media.objects.size, 0);
  assert.equal(media.puts.length, 0);
});

test('upload endpoint: malformed binary with image MIME is rejected (422)', async () => {
  const db = createTestDb();
  const media = new FakeMedia();
  const junk = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x00, 0x00, 0x00, 0x00, 0xff, 0xfe, 0xfd]);
  const res = await upload(media, db, withFile(new File([junk], 'broken.png', { type: 'image/png' })));
  assert.equal(res.status, 422);
  assert.equal((await countImages(db)), 0);
  assert.equal(media.objects.size, 0);
});

test('upload endpoint: unsupported MIME is rejected (415)', async () => {
  const db = createTestDb();
  const media = new FakeMedia();
  const res = await upload(media, db, withFile(new File(['x'.repeat(64)], 'a.gif', { type: 'image/gif' })));
  assert.equal(res.status, 415);
  assert.equal((await countImages(db)), 0);
  assert.equal(media.objects.size, 0);
});

test('upload endpoint: declared MIME mismatching the real contents is rejected (422)', async () => {
  const db = createTestDb();
  const media = new FakeMedia();
  const realPng = await fixture('image/png');
  const res = await upload(media, db, withFile(new File([realPng], 'fake.jpg', { type: 'image/jpeg' })));
  assert.equal(res.status, 422);
  assert.equal((await countImages(db)), 0);
  assert.equal(media.objects.size, 0);
});

test('upload endpoint: oversized payload is rejected (413)', async () => {
  const db = createTestDb();

  // Building a >20MB multipart body by hand would be slow; cap the fixture to a
  // size the handler rejects by temporarily lowering the cap via a large file.
  const big = new Uint8Array(21 * 1024 * 1024); // 21MB of zeros
  const res = await upload(new FakeMedia(), db, withFile(new File([big], 'big.png', { type: 'image/png' })));
  assert.equal(res.status, 413);
  assert.equal((await countImages(db)), 0);
});

// ---------- failure cleanup: D1 insert fails AFTER R2 put ----------

/** Wraps a real db so the images INSERT rejects, simulating a D1 failure. */
function failingInsertDb(db: D1Like): D1Like {
  return {
    prepare(sql: string): D1StatementLike {
      if (/^\s*INSERT INTO images/i.test(sql)) {
        return { bind() { return this; }, first: async () => null, all: async () => ({ results: [] as never[] }), run: async () => { throw new Error('D1_ERROR: simulated insert failure'); } };
      }
      return db.prepare(sql);
    },
  };
}

test('upload endpoint: R2 object is removed when the D1 insert fails', async () => {
  const realDb = createTestDb();
  const media = new FakeMedia();
  const res = await upload(media, failingInsertDb(realDb), withFile(new File([await fixture('image/png')], 'photo.png', { type: 'image/png' })));

  assert.equal(res.status, 500);
  assert.equal((await countImages(realDb)), 0, "no D1 row");
  assert.equal(media.objects.size, 0, 'R2 object deleted after failed insert');
  assert.equal(media.puts.length, 1, 'R2 put happened once');
  assert.equal(media.deletes.length, 1, 'cleanup delete happened once');
  assert.deepEqual(media.deletes, media.puts, 'deleted the same key that was put');
});

// ---------- retrieval regression (the public /images/[id] route path) ----------

test('upload endpoint: stored image can be looked up for the public route and returns 404 for unknown ids', async () => {
  const db = createTestDb();
  const media = new FakeMedia();
  const res = await upload(media, db, withFile(new File([await fixture('image/webp')], 'photo.webp', { type: 'image/webp' })));
  assert.equal(res.status, 200);
  const image = await resImage(res);

  const row = await db.prepare('SELECT r2_original, mime FROM images WHERE id = ?').bind(image.id).first<{ r2_original: string; mime: string }>();
  assert.ok(row, 'D1 lookup works for the public route');
  assert.ok(media.objects.has(row!.r2_original));
  assert.equal(row!.mime, 'image/webp');
  assert.equal(media.objects.get(row!.r2_original)!.byteLength, image.bytes);

  const missing = await db.prepare('SELECT 1 AS x FROM images WHERE id = ?').bind('00000000-0000-4000-8000-000000000000').first();
  assert.equal(missing, null, 'unknown id resolves to nothing (the public route 404s)');
});